### ISSUE TITLE
请问大佬：在JNI层是否用过动态加载的方式调用SO库

### ISSUE THREAD

**Issue by Jinzhou160225** [ConorPai/AndroidStudio-NDK-Test#1]

**Comment by ConorPai** [comment]
我不是专门做安卓的，这方面认识也不是很深，不过可以和你讨论一下。
没太看懂你说的动态加载的意思是什么，能具体描述一下使用场景是什么，想达到什么目标之类的~

**Comment by Jinzhou160225** [comment]
我也不是专门做安卓的。。其实就是在JNI层写一个动态加载SO库的函数，比如使用dlopen函数。然后再外面使用NDK，写mk脚本编译成so。放到工程里，之后动态加载里面的函数。至于目标也是要使用so库里的函数啊

**Comment by ConorPai** [comment]
我做了个简单的测试，调是用没问题的，代码上传了，你看一下是不是你想要的那种

**Comment by Jinzhou160225** [comment]
感谢，我学习一下

**Comment by ConorPai** [comment]
close issue
